CREATE TABLE role_permissions
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    permission VARCHAR(255)                            NOT NULL,
    enabled    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (id)
);

INSERT INTO role_permissions (role, permission, enabled) VALUES ('ROLE_ADMIN', 'PAGE1_READ', true);
INSERT INTO role_permissions (role, permission, enabled) VALUES ('ROLE_ADMIN', 'PAGE1_WRITE', true);
INSERT INTO role_permissions (role, permission, enabled) VALUES ('ROLE_USER', 'PAGE2_READ', true);
INSERT INTO role_permissions (role, permission, enabled) VALUES ('ROLE_USER', 'PAGE2_WRITE', false);
